server:
  port: 7070

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/java11AuthDBtekrar

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secretKey: ${java11secretkey}
  issuer: ${java11issuer}
  audience: ${java11audience}